name: servermanager
description: A flutter application that manages my linux server.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  #* App Architecture
  get_it: ^4.0.2
  stacked: ^1.6.0
  stacked_services: ^0.4.1

  #* Navigation
  auto_route: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Navigation
  auto_route_generator: ^0.5.0
  build_runner: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/secrets/appsettings.json